MetaDataFormat: "yaml"
baseurl: "http://dogsbuttbrew.com/"
languageCode: "en-us"
title: "The Hydrant"
theme: "liquorice"
params:
  description: "Web home for Brandon Grady."
  author: "Brandon Grady"
