MetaDataFormat: "yaml"
baseurl: "http://dogsbuttbrew.com/"
languageCode: "en-us"
title: "The Hydrant"
theme: "liquorice"
publishdir: "_site"
builddrafts: false
permalinks:
  post: /post/:year/:month/:title
params:
  description: "Web home for Brandon Grady."
  author: "Brandon Grady"
