MetaDataFormat: "yaml"
baseurl: "http://dogsbuttbrew.com/"
languageCode: "en-us"
title: "The Hydrant"
theme: "dbb-liquorice"
publishdir: "_site"
builddrafts: false
disqusShortname: "dogsbuttbrewcom"
permalinks:
  post: /post/:year/:month/:title
params:
  description: "Web home for Brandon Grady."
  author: "Brandon Grady"

menu:
  main:
    - Name: "About"
      Weight: 0
      Identifier: "about"
      URL: "/about/"
    - Name: "Family"
      Weight: 1
      Identifier: "family"
      URL: "/categories/family/"
    - Name: "Categories"
      Weight: 2
      Identifier: "categories"
      URL: "/categories/"
    - Name: "Old Site"
      Weight: 2
      Identifier: "old-site"
      URL: "/old-site/"
